### PR TITLE
Use calcLinearState in pairwise factor creation

### LINKED ISSUE #14: DaiCRF doesn't respect edge direction.
There is a [failing test](https://github.com/pystruct/pystruct/blob/master/tests/test_inference/test_exact_inference.py), caused by an error in the DAI wrappers. @vene noticed something was awry. It seems the setting of the pairwise potentials is not as straight-forward as I thought. I think one might need to use [calcLinearState](http://cs.ru.nl/~jorism/libDAI/doc/namespacedai.html#a750c3807e7375265c3fb410a1f1223fe).
Any help appreciated ;)

### PR DESCRIPTION
**Pull request by vene**
Fixes https://github.com/pystruct/pystruct/issues/14 and boosts my hacking morale.

### CODE REVIEW

**Comment by amueller** [comment]
yes please. Have you checked with the pystruct test I pointed to?

**Comment by amueller** [comment]
:+1: for hacking morale ;)

**Comment by vene** [comment]
Test passes, inference is correct on my joint chain too ;)

**Comment by amueller** [comment]
sweet, thank you so much! Is it now working as good as ad3? Also how does it compare in terms of speed? Could you send the commit with the construction in the outer loop?

**Comment by vene** [comment]
Strangely it seems slightly slower than AD3, though I remember finding it
to be faster before.

**Comment by amueller** [comment]
For chains it should be faster, for loopy things, it is plausible that it is slower.

**Comment by amueller** [comment]
oh you should compare it with `ad3bb` btw. `ad3` doesn't solve it exactly every time, it solves the lp relaxation.

**Comment by vene** [comment]
I will redo the comparison with the full feature set and following your
advice.  Sadly I used `ad3` not `ad3bb` in my paper so there might not be a
significant time gain from this.

**Comment by amueller** [comment]
well, then you can at least expect the exact result in a similar time ;)

**Comment by amueller** [comment]
Ok, merging.

**Pull request merged**
